baseURL = 'https://yangyang.dev/'
languageCode = 'en-us'
title = 'yangyang dev blog'
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
featured_image = 'https://res.cloudinary.com/dkmuoufxh/image/upload/v1676599212/back1_bjnsmr.jpg'
disqusShortname = 'yangyang-dev'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "yangyang"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  commentoEnable = true
